### PR TITLE
🐛 Fix errors on player disconnect

### LINKED ISSUE #60: Fix error thrown when socket disconnects by closing tab/browser
https://github.com/fre-ben/sisu/pull/59/commits/8c31806f3d897a855d18f5d875ada63f50335051

### PR DESCRIPTION
**Pull request by fre-ben**
Previously the gamestate wasn't changed when a player left a game by closing the tab/browser.
Also errors occured in the server log when a player closed the tab/browser while not being in a game

It's fixed for now, but limits the lobbies to 20.
Above 20 lobbies the error will occur again.

In order to fix that, I need to figure out how to get the amount of Lobbies currently created.

Deployment:
Fixes #60 in part

### CODE REVIEW

File: server/lib/games.ts [hunk 1]
```diff
@@ -158,3 +158,7 @@ export function getDiscardPile(lobbyNr: number): Card {
   const discardpile = getGameByLobby(lobbyNr).discardPileCards;
   return discardpile[discardpile.length - 1];
 }
+
+export function getNumberOfGames() {
+  return games[[].length];
```
Comment (lmachens) [inline server/lib/games.ts]: `[].length` returns `0` in any case. Thus, you access `games[0]`  (first element) every time.

**Review by lmachens — COMMENTED** [review]
I am not sure if this `rooms` logic is required.
What happens, when you do this?

```ts
socket.on("disconnect", async () => {
      console.log(socket.id + " disconnected");
      const lobbyNr = (await getGame(socket.id)).lobbyNr;
      
      await leaveGame(socket.id);
      broadcastTotalScoresToLobby(io, lobbyNr);
      broadcastPlayerCountToLobby(io, lobbyNr);
      broadcastPlayersToLobby(io, lobbyNr);
      broadcastListGamesUpdate();
})
```

The only difference is, that you get the `lobbyNr` before you leave the game.

**Review by DNaunin — APPROVED** [review]
LGTM! 🐰

**Comment by fre-ben** [comment]
> I am not sure if this `rooms` logic is required.
> What happens, when you do this?
> 
> ```ts
> socket.on("disconnect", async () => {
>       console.log(socket.id + " disconnected");
>       const lobbyNr = (await getGame(socket.id)).lobbyNr;
>       
>       await leaveGame(socket.id);
>       broadcastTotalScoresToLobby(io, lobbyNr);
>       broadcastPlayerCountToLobby(io, lobbyNr);
>       broadcastPlayersToLobby(io, lobbyNr);
>       broadcastListGamesUpdate();
> })
> ```
> 
> The only difference is, that you get the `lobbyNr` before you leave the game.

@lmachens That was the initial state which caused the following error in the server log:
```
(node:2273) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'lobbyNr' of undefined
    at Socket.<anonymous> (/home/bend3r/dev/sisu/server/socket.ts:64:50)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2273) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:2273) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

That's why I need to loop through the games and check if the player is connected to a lobby. 
Otherwise the functions in `disconnecting` will try to fetch a game which doesn't exist - or rather a lobby which the player isn't connected to.

File: server/lib/games.ts (hunk 1 above)
Comment (fre-ben) [reply server/lib/games.ts]: This doesn't work either, as it returns the whole game :(
` return games[[0].length]`
Returns a game object.

`return games[0].length`
Doesn't work, since it isn't an array and doesn't allow the length property.
